name: Deploy to ECS (from ECR)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. AWS Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Get current task definition
      - name: Get task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition task-def-1 \
            --query taskDefinition > task-definition.json

      # 3. Fix JSON + update image
      - name: Update task definition
        run: |
          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
          task-definition.json > new-task-def.json

          sed -i 's|image":.*|image": "439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest",|' new-task-def.json

      # 4. Register new revision
      - name: Register task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json

      # 5. Deploy to ECS
      - name: Deploy
        run: |
          aws ecs update-service \
            --cluster ecs \
            --service task-def-1-service-5pv5guf8 \
            --force-new-deployment
