name: Build, Push and Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. AWS Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Image
      - name: Build
        run: |
          docker build -t naveen .

      # 5. Tag Image
      - name: Tag
        run: |
          docker tag naveen:latest 439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest

      # 6. Push Image
      - name: Push
        run: |
          docker push 439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest

      # 7. Update Task Definition
      - name: Download existing task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition task-def-1 \
            --query taskDefinition > task-definition.json

      - name: Update image in task definition
        run: |
          sed -i 's|image":.*|image": "439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest",|' task-definition.json

      # 8. Register new revision
      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://task-definition.json

      # 9. Deploy to ECS Service
      - name: Deploy service
        run: |
          aws ecs update-service \
            --cluster ecs \
            --service task-def-1-service-5pv5guf8 \
            --force-new-deployment
