name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Image
        run: |
          docker build -t naveen .

      # Tag Image
      - name: Tag Image
        run: |
          docker tag naveen:latest 439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest

      # Push Image
      - name: Push Image
        run: |
          docker push 439481669447.dkr.ecr.us-east-1.amazonaws.com/naveen:latest
